language: r
cache: packages
r:
  - release

r_check_args: --as-cran

warnings_are_errors: true

sudo: false

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  include:
    - os: linux
      env: BLAS=OpenBLAS
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
             # compilers
            - g++
            - gfortran
              # math libraries
            - libopenblas-base
    - os: linux

cache: packages
