# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fit_gamma_cpp <- function(X_, Y_, groups_, unique_groups_, group_weights_, weights_, offset_, lambda_, nlambda, lambda_min_ratio, tau, maxit, tol, maxit_irls, tol_irls, intercept, penalty, strongrule) {
    .Call(`_personalized2part_fit_gamma_cpp`, X_, Y_, groups_, unique_groups_, group_weights_, weights_, offset_, lambda_, nlambda, lambda_min_ratio, tau, maxit, tol, maxit_irls, tol_irls, intercept, penalty, strongrule)
}

fit_twopart_cpp <- function(X_, Z_, Xs_, S_, groups_, unique_groups_, group_weights_, weights_, weights_s_, offset_, offset_s_, lambda_, nlambda, lambda_min_ratio, tau, maxit, tol, maxit_irls, tol_irls, intercept_z, intercept_s, penalty, opposite_signs, strongrule, balance_likelihoods) {
    .Call(`_personalized2part_fit_twopart_cpp`, X_, Z_, Xs_, S_, groups_, unique_groups_, group_weights_, weights_, weights_s_, offset_, offset_s_, lambda_, nlambda, lambda_min_ratio, tau, maxit, tol, maxit_irls, tol_irls, intercept_z, intercept_s, penalty, opposite_signs, strongrule, balance_likelihoods)
}

