# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mmbcd_cpp <- function(X, Y, groups, unique_groups, group_weights, weights, lambda, nlambda, lambda_min_ratio, maxit, tol, intercept, family, penalty) {
    .Call(`_personalized2part_mmbcd_cpp`, X, Y, groups, unique_groups, group_weights, weights, lambda, nlambda, lambda_min_ratio, maxit, tol, intercept, family, penalty)
}

mmbcd_gaussian_cpp <- function(X, Y, groups, unique_groups, group_weights, weights, lambda, nlambda, lambda_min_ratio, maxit, tol, intercept) {
    .Call(`_personalized2part_mmbcd_gaussian_cpp`, X, Y, groups, unique_groups, group_weights, weights, lambda, nlambda, lambda_min_ratio, maxit, tol, intercept)
}

mmbcd_twopart_cpp <- function(X, Z, Xs, S, groups, unique_groups, group_weights, weights, weights_s, lambda, nlambda, lambda_min_ratio, maxit, tol, intercept, penalty) {
    .Call(`_personalized2part_mmbcd_twopart_cpp`, X, Z, Xs, S, groups, unique_groups, group_weights, weights, weights_s, lambda, nlambda, lambda_min_ratio, maxit, tol, intercept, penalty)
}

